company-slider-section added
tcet-opensource/practice-react pull request #19
Opened 2023-09-04 03:45 UTC by prachii79

2023-09-04 18:32 UTC, shlok-2003 commented on src/components/Company-Slider/index.jsx
> +import React, { useRef, useState } from 'react';
`No need to import React. Hooks are not being used so again, no need for import`

2023-09-05 16:20 UTC, Rahilsiddique requested changes

2023-09-05 16:20 UTC, Rahilsiddique commented on src/globals.css
> +@layer base {
avoid adding styles directly to html or * 
try to do it in your own component

2023-09-05 16:20 UTC, Rahilsiddique commented on src/components/Company-Slider/CompanySwiper.jsx
> +      <Swiper
if possible try to add `cursor-pointer` when hovered over slider navigation

2023-09-07 11:20 UTC, merged